name: = building app 
on: push
jobs: 
   build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list files after Checkou
        run: |
          echo "Files in the repository:"
          ls -la
      - name: install node js 
        uses: actions/setup-node@v4
        with: 
                node-version: '20.x'
      - name: install the dependency 
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
           